"""learning_words

Revision ID: 3b741d9bac1a
Revises: 665ecf3a245e
Create Date: 2026-06-19 08:39:42.844512+00:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision: str = '3b741d9bac1a'
down_revision: str | None = '665ecf3a245e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learned_words',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('word_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word_id', name='uq_learned_words_user_id_word_id')
    )
    op.create_index(op.f('ix_learned_words_user_id'), 'learned_words', ['user_id'], unique=False)
    op.create_index(op.f('ix_learned_words_word_id'), 'learned_words', ['word_id'], unique=False)
    op.drop_index(op.f('ix_user_words_user_id'), table_name='user_words')
    op.drop_index(op.f('ix_user_words_word_id'), table_name='user_words')
    op.drop_table('user_words')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_words',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('word_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_words_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], name=op.f('user_words_word_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_words_pkey')),
    sa.UniqueConstraint('user_id', 'word_id', name=op.f('uq_user_words_user_id_word_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_words_word_id'), 'user_words', ['word_id'], unique=False)
    op.create_index(op.f('ix_user_words_user_id'), 'user_words', ['user_id'], unique=False)
    op.drop_index(op.f('ix_learned_words_word_id'), table_name='learned_words')
    op.drop_index(op.f('ix_learned_words_user_id'), table_name='learned_words')
    op.drop_table('learned_words')
    # ### end Alembic commands ###
