"""lenght_enum_columns

Revision ID: 3e77d09daebc
Revises: 87ee26ddc861
Create Date: 2026-08-27 08:11:27.455105+00:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '3e77d09daebc'
down_revision: str | None = '87ee26ddc861'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('learned_word_status'), 'learned_words', type_='check')
    op.drop_constraint(op.f('ai_request_initiator'), 'text_model_usages', type_='check')
    op.drop_constraint(op.f('ai_request_scenario'), 'text_model_usages', type_='check')
    op.alter_column('learned_words', 'status',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('new', 'familiar', 'learned', name='learned_word_status', native_enum=False, create_constraint=True, length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'new'::character varying"))
    op.alter_column('text_model_usages', 'initiator',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('system', 'user', name='ai_request_initiator', native_enum=False, create_constraint=True, length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'system'::character varying"))
    op.alter_column('text_model_usages', 'scenario',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('word_review', 'word_answer_check', name='ai_request_scenario', native_enum=False, create_constraint=True, length=50),
               existing_nullable=False)
    op.create_index(op.f('ix_user_sessions_session_id'), 'user_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_index('ix_word_repetition_answers_user_word_created_id', 'word_repetition_answers', ['user_id', 'word_id', 'created_at', 'id'], unique=False)
    op.alter_column('words_en', 'country',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.Enum('us', 'gb', 'both', name='word_country', native_enum=False, length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'both'::character varying"))
    op.alter_column('words_en', 'source',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Enum('base', 'gpt', 'admin', 'user', name='word_source', native_enum=False, create_constraint=True, length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'default'::character varying"))
    op.alter_column('words_en', 'status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('allowed', 'checking', 'manual_review', 'forbidden', name='word_status', native_enum=False, length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'allowed'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('words_en', 'status',
               existing_type=sa.Enum('allowed', 'checking', 'manual_review', 'forbidden', name='word_status', native_enum=False, length=50),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False,
               existing_server_default=sa.text("'allowed'::character varying"))
    op.alter_column('words_en', 'source',
               existing_type=sa.Enum('base', 'gpt', 'admin', 'user', name='word_source', native_enum=False, create_constraint=True, length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("'default'::character varying"))
    op.alter_column('words_en', 'country',
               existing_type=sa.Enum('us', 'gb', 'both', name='word_country', native_enum=False, length=50),
               type_=sa.VARCHAR(length=4),
               existing_nullable=False,
               existing_server_default=sa.text("'both'::character varying"))
    op.drop_index('ix_word_repetition_answers_user_word_created_id', table_name='word_repetition_answers')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_session_id'), table_name='user_sessions')
    op.create_check_constraint(op.f('ai_request_scenario'), 'text_model_usages', "scenario::text = 'word_review'::text")
    op.create_check_constraint(op.f('ai_request_initiator'), 'text_model_usages', "initiator::text = ANY (ARRAY['system'::character varying, 'user'::character varying]::text[])")
    op.alter_column('text_model_usages', 'scenario',
               existing_type=sa.Enum('word_review', 'word_answer_check', name='ai_request_scenario', native_enum=False, create_constraint=True, length=50),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.alter_column('text_model_usages', 'initiator',
               existing_type=sa.Enum('system', 'user', name='ai_request_initiator', native_enum=False, create_constraint=True, length=50),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False,
               existing_server_default=sa.text("'system'::character varying"))
    op.create_check_constraint(op.f('learned_word_status'), 'learned_words', "status::text = ANY (ARRAY['new'::character varying, 'learned'::character varying]::text[])")
    op.alter_column('learned_words', 'status',
               existing_type=sa.Enum('new', 'familiar', 'learned', name='learned_word_status', native_enum=False, create_constraint=True, length=50),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False,
               existing_server_default=sa.text("'new'::character varying"))
    # ### end Alembic commands ###
