"""add_synonyms

Revision ID: 450e57de2577
Revises: 665ecf3a245e
Create Date: 2026-07-20 06:59:36.962562+00:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '450e57de2577'
down_revision: str | None = '665ecf3a245e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_en_synonyms',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('word_en_id', sa.BigInteger(), nullable=False),
    sa.Column('synonym_word_en_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('word_en_id <> synonym_word_en_id', name='ck_word_en_synonyms_not_self'),
    sa.ForeignKeyConstraint(['synonym_word_en_id'], ['words_en.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_en_id'], ['words_en.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word_en_id', 'synonym_word_en_id', name='uq_word_en_synonyms_word_en_id_synonym_word_en_id')
    )
    op.create_index(op.f('ix_word_en_synonyms_synonym_word_en_id'), 'word_en_synonyms', ['synonym_word_en_id'], unique=False)
    op.create_index(op.f('ix_word_en_synonyms_word_en_id'), 'word_en_synonyms', ['word_en_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_en_synonyms_word_en_id'), table_name='word_en_synonyms')
    op.drop_index(op.f('ix_word_en_synonyms_synonym_word_en_id'), table_name='word_en_synonyms')
    op.drop_table('word_en_synonyms')
    # ### end Alembic commands ###
