"""word_review

Revision ID: 499819deaab0
Revises: 450e57de2577
Create Date: 2026-07-20 13:42:50.069730+00:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '499819deaab0'
down_revision: str | None = '450e57de2577'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words_en', sa.Column('is_reviewed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words_en', 'is_reviewed')
    # ### end Alembic commands ###
