"""text_usage

Revision ID: 55f1f05522b0
Revises: 499819deaab0
Create Date: 2026-07-22 14:37:18.612888+00:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '55f1f05522b0'
down_revision: str | None = '499819deaab0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_model_usages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('initiator', sa.Enum('system', 'user', name='ai_request_initiator', native_enum=False, create_constraint=True), server_default='system', nullable=False),
    sa.Column('scenario', sa.Enum('word_review', name='ai_request_scenario', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_input_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('reasoning_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text_model_usages')
    # ### end Alembic commands ###
