"""add_session_logs

Revision ID: 87ee26ddc861
Revises: 8c62f4a3d9e1
Create Date: 2026-08-26 14:58:38.107028+00:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '87ee26ddc861'
down_revision: str | None = '8c62f4a3d9e1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('words_en', 'status',
               existing_type=sa.Enum('allowed', 'checking', 'manual_review', 'forbidden', name='word_status', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False,
               existing_server_default=sa.text("'allowed'::character varying"))
    op.drop_index('ix_word_repetition_answers_user_word_created_id', table_name='word_repetition_answers')
    op.create_check_constraint(op.f('ai_request_scenario'), 'text_model_usages', "scenario::text = 'word_review'::text")
    op.create_check_constraint(op.f('ai_request_initiator'), 'text_model_usages', "initiator::text = ANY (ARRAY['system'::character varying, 'user'::character varying]::text[])")
    op.alter_column('text_model_usages', 'scenario',
               existing_type=sa.Enum('word_review', 'word_answer_check', name='ai_request_scenario', native_enum=False, create_constraint=True, length=50),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.create_check_constraint(op.f('learned_word_status'), 'learned_words', "status::text = ANY (ARRAY['new'::character varying, 'learned'::character varying]::text[])")
    op.alter_column('learned_words', 'status',
               existing_type=sa.Enum('new', 'familiar', 'learned', name='learned_word_status', native_enum=False, create_constraint=True),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False,
               existing_server_default=sa.text("'new'::character varying"))
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_session_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    # ### end Alembic commands ###
