"""add_language_level

Revision ID: 9cc445da784e
Revises: e6d8b1810d85
Create Date: 2026-08-13 06:20:32.798160+00:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9cc445da784e'
down_revision: str | None = 'e6d8b1810d85'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


LANGUAGE_LEVELS = (
    {'name': 'A1', 'grade': 1},
    {'name': 'A2', 'grade': 2},
    {'name': 'B1', 'grade': 3},
    {'name': 'B2', 'grade': 4},
    {'name': 'C1', 'grade': 5},
    {'name': 'C2', 'grade': 6},
)

LANGUAGE_LEVELS_TABLE = sa.table(
    'language_levels',
    sa.column('id', sa.BigInteger),
    sa.column('name', sa.String),
    sa.column('grade', sa.SmallInteger),
)

WORDS_EN_TABLE = sa.table(
    'words_en',
    sa.column('id', sa.BigInteger),
    sa.column('level', sa.String),
    sa.column('level_id', sa.BigInteger),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language_levels',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('grade', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('grade BETWEEN 1 AND 6', name='ck_language_levels_grade_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_language_levels_grade'), 'language_levels', ['grade'], unique=True)
    op.create_index(op.f('ix_language_levels_name'), 'language_levels', ['name'], unique=True)
    _seed_language_levels()
    # op.drop_index(op.f('ix_text_model_usages_session_id'), table_name='text_model_usages')
    # op.drop_column('text_model_usages', 'session_id')
    op.add_column('words_en', sa.Column('level_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_words_en_level_id'), 'words_en', ['level_id'], unique=False)
    op.create_foreign_key(
        'fk_words_en_level_id_language_levels',
        'words_en',
        'language_levels',
        ['level_id'],
        ['id'],
        ondelete='RESTRICT',
    )
    _backfill_word_level_ids()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_words_en_level_id_language_levels',
        'words_en',
        type_='foreignkey',
    )
    op.drop_index(op.f('ix_words_en_level_id'), table_name='words_en')
    op.drop_column('words_en', 'level_id')
    # op.add_column('text_model_usages', sa.Column('session_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # op.create_index(op.f('ix_text_model_usages_session_id'), 'text_model_usages', ['session_id'], unique=False)
    op.drop_index(op.f('ix_language_levels_name'), table_name='language_levels')
    op.drop_index(op.f('ix_language_levels_grade'), table_name='language_levels')
    op.drop_table('language_levels')
    # ### end Alembic commands ###


def _seed_language_levels() -> None:
    op.bulk_insert(LANGUAGE_LEVELS_TABLE, list(LANGUAGE_LEVELS))


def _backfill_word_level_ids() -> None:
    connection = op.get_bind()
    language_levels = connection.execute(
        sa.select(
            LANGUAGE_LEVELS_TABLE.c.id,
            LANGUAGE_LEVELS_TABLE.c.name,
        ),
    ).all()
    level_ids_by_name = {
        language_level.name.strip().upper(): language_level.id for language_level in language_levels
    }

    words = connection.execute(
        sa.select(
            WORDS_EN_TABLE.c.id,
            WORDS_EN_TABLE.c.level,
        ),
    ).all()

    for word in words:
        if word.level is None:
            continue

        level_id = level_ids_by_name.get(word.level.strip().upper())
        if level_id is None:
            continue

        connection.execute(
            sa.update(WORDS_EN_TABLE)
            .where(WORDS_EN_TABLE.c.id == word.id)
            .values(level_id=level_id),
        )
