"""initial_schema

Revision ID: b0af56d0b8ea
Revises: 
Create Date: 2026-07-10 14:46:13.623762+00:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = 'b0af56d0b8ea'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('words_en',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('pronunciation', sa.String(length=255), nullable=True),
    sa.Column('part_of_speech', sa.String(length=100), nullable=True),
    sa.Column('country', sa.Enum('us', 'gb', 'both', name='word_country', native_enum=False), server_default='both', nullable=False),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('audio_file_name', sa.String(length=255), nullable=True),
    sa.Column('audio_tg_id', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=255), server_default='default', nullable=False),
    sa.Column('status', sa.Enum('allowed', 'forbidden', name='word_status', native_enum=False), server_default='allowed', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word', 'part_of_speech', name='uq_words_en_word_part_of_speech')
    )
    op.create_index(op.f('ix_words_en_word'), 'words_en', ['word'], unique=False)
    op.create_table('answer_errors',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('word_id', sa.BigInteger(), nullable=False),
    sa.Column('answer_type', sa.String(length=20), nullable=False),
    sa.Column('answer_language', sa.String(length=10), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('has_typo', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('typo_type', sa.String(length=20), nullable=True),
    sa.Column('typo_index', sa.Integer(), nullable=True),
    sa.Column('expected', sa.String(length=10), nullable=True),
    sa.Column('actual', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words_en.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_errors_user_id'), 'answer_errors', ['user_id'], unique=False)
    op.create_index(op.f('ix_answer_errors_word_id'), 'answer_errors', ['word_id'], unique=False)
    op.create_table('learned_words',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('word_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words_en.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word_id', name='uq_learned_words_user_id_word_id')
    )
    op.create_index(op.f('ix_learned_words_user_id'), 'learned_words', ['user_id'], unique=False)
    op.create_index(op.f('ix_learned_words_word_id'), 'learned_words', ['word_id'], unique=False)
    op.create_table('words_ru',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('word_en_id', sa.BigInteger(), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['word_en_id'], ['words_en.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word_en_id', 'word', name='uq_words_ru_word_en_id_word')
    )
    op.create_index(op.f('ix_words_ru_word'), 'words_ru', ['word'], unique=False)
    op.create_index(op.f('ix_words_ru_word_en_id'), 'words_ru', ['word_en_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_words_ru_word_en_id'), table_name='words_ru')
    op.drop_index(op.f('ix_words_ru_word'), table_name='words_ru')
    op.drop_table('words_ru')
    op.drop_index(op.f('ix_learned_words_word_id'), table_name='learned_words')
    op.drop_index(op.f('ix_learned_words_user_id'), table_name='learned_words')
    op.drop_table('learned_words')
    op.drop_index(op.f('ix_answer_errors_word_id'), table_name='answer_errors')
    op.drop_index(op.f('ix_answer_errors_user_id'), table_name='answer_errors')
    op.drop_table('answer_errors')
    op.drop_index(op.f('ix_words_en_word'), table_name='words_en')
    op.drop_table('words_en')
    op.drop_table('users')
    # ### end Alembic commands ###
