"""add_status_answered

Revision ID: b60f39a3b5b4
Revises: 3e77d09daebc
Create Date: 2026-09-01 15:39:23.290167+00:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = 'b60f39a3b5b4'
down_revision: str | None = '3e77d09daebc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('learned_word_status'), 'learned_words', type_='check')
    op.drop_constraint(op.f('ai_request_initiator'), 'text_model_usages', type_='check')
    op.drop_constraint(op.f('ai_request_scenario'), 'text_model_usages', type_='check')
    op.add_column('word_repetition_answers', sa.Column('word_status', sa.Enum('new', 'familiar', 'learned', name='word_repetition_answer_word_status', native_enum=False, create_constraint=True, length=50), server_default='new', nullable=False))
    op.drop_constraint(op.f('word_source'), 'words_en', type_='check')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f('word_source'), 'words_en', "source::text = ANY (ARRAY['base'::character varying, 'gpt'::character varying, 'admin'::character varying, 'user'::character varying]::text[])")
    op.drop_column('word_repetition_answers', 'word_status')
    op.create_check_constraint(op.f('ai_request_scenario'), 'text_model_usages', "scenario::text = ANY (ARRAY['word_review'::character varying, 'word_answer_check'::character varying]::text[])")
    op.create_check_constraint(op.f('ai_request_initiator'), 'text_model_usages', "initiator::text = ANY (ARRAY['system'::character varying, 'user'::character varying]::text[])")
    op.create_check_constraint(op.f('learned_word_status'), 'learned_words', "status::text = ANY (ARRAY['new'::character varying, 'familiar'::character varying, 'learned'::character varying]::text[])")
    # ### end Alembic commands ###
