"""word_answers

Revision ID: d7a1a84899ae
Revises: 55f1f05522b0
Create Date: 2026-07-31 12:12:57.534502+00:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = 'd7a1a84899ae'
down_revision: str | None = '55f1f05522b0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_repetition_answers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('word_id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words_en.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_repetition_answers_session_id'), 'word_repetition_answers', ['session_id'], unique=False)
    op.create_index('ix_word_repetition_answers_user_word_correct_created', 'word_repetition_answers', ['user_id', 'word_id', 'is_correct', 'created_at'], unique=False)
    op.add_column('learned_words', sa.Column('review_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('learned_words', sa.Column('status', sa.Enum('new', 'learned', name='learned_word_status', native_enum=False, create_constraint=True), server_default='new', nullable=False))
    op.add_column('learned_words', sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learned_words', 'last_reviewed_at')
    op.drop_column('learned_words', 'status')
    op.drop_column('learned_words', 'review_count')
    op.drop_index('ix_word_repetition_answers_user_word_correct_created', table_name='word_repetition_answers')
    op.drop_index(op.f('ix_word_repetition_answers_session_id'), table_name='word_repetition_answers')
    op.drop_table('word_repetition_answers')
    # ### end Alembic commands ###
