"""initial tables

Revision ID: e197b367fe3d
Revises: 
Create Date: 2026-06-17 11:47:00.900210+00:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = 'e197b367fe3d'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('words',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('pronunciation', sa.String(length=255), nullable=True),
    sa.Column('translation', sa.String(length=255), nullable=False),
    sa.Column('part_of_speech', sa.String(length=100), nullable=True),
    sa.Column('country', sa.Enum('us', 'gb', 'both', name='word_country', native_enum=False), server_default='both', nullable=False),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('audio_file_name', sa.String(length=255), nullable=True),
    sa.Column('audio_tg_id', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=255), server_default='default', nullable=False),
    sa.Column('status', sa.Enum('allowed', 'forbidden', name='word_status', native_enum=False), server_default='allowed', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word', 'part_of_speech', name='uq_words_word_part_of_speech')
    )
    op.create_index(op.f('ix_words_word'), 'words', ['word'], unique=False)
    op.create_table('user_words',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('word_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word_id', name='uq_user_words_user_id_word_id')
    )
    op.create_index(op.f('ix_user_words_user_id'), 'user_words', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_words_word_id'), 'user_words', ['word_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_words_word_id'), table_name='user_words')
    op.drop_index(op.f('ix_user_words_user_id'), table_name='user_words')
    op.drop_table('user_words')
    op.drop_index(op.f('ix_words_word'), table_name='words')
    op.drop_table('words')
    op.drop_table('users')
    # ### end Alembic commands ###
