"""user_settings

Revision ID: e6d8b1810d85
Revises: d7a1a84899ae
Create Date: 2026-08-05 12:55:53.385080+00:00
"""

from collections.abc import Sequence
import hashlib

from alembic import op
import sqlalchemy as sa



revision: str = 'e6d8b1810d85'
down_revision: str | None = 'd7a1a84899ae'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _get_legacy_session_id() -> str:
    return hashlib.sha256(b'legacy-session').hexdigest()


def _backfill_session_ids() -> None:
    legacy_session_id = _get_legacy_session_id()

    for table_name in ('learned_words', 'word_repetition_answers'):
        table = sa.table(
            table_name,
            sa.column('session_id', sa.String(length=64)),
        )
        op.execute(
            table.update()
            .where(table.c.session_id.is_(None))
            .values(session_id=op.inline_literal(legacy_session_id)),
        )


def _clear_legacy_session_ids() -> None:
    legacy_session_id = _get_legacy_session_id()

    for table_name in ('learned_words', 'word_repetition_answers'):
        table = sa.table(
            table_name,
            sa.column('session_id', sa.String(length=64)),
        )
        op.execute(
            table.update()
            .where(
                table.c.session_id == op.inline_literal(legacy_session_id),
            )
            .values(session_id=None),
        )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    _backfill_session_ids()
    op.alter_column('learned_words', 'session_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('word_repetition_answers', 'session_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('word_repetition_answers', 'session_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('learned_words', 'session_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    _clear_legacy_session_ids()
    op.drop_table('user_settings')
    # ### end Alembic commands ###
