"""add_columns_settings_tz_and_level

Revision ID: f6d53778d132
Revises: 1f6b5d2a8c41
Create Date: 2026-08-13 09:28:56.945557+00:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = 'f6d53778d132'
down_revision: str | None = '1f6b5d2a8c41'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('selected_language_level_id', sa.BigInteger(), nullable=True))
    op.add_column('user_settings', sa.Column('system_language_level_id', sa.BigInteger(), nullable=True))
    op.add_column('user_settings', sa.Column('reminders_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('user_settings', sa.Column('reminder_time', sa.Time(), server_default='20:00:00', nullable=False))
    op.alter_column('user_settings', 'timezone',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_server_default=sa.text("'UTC'::character varying"))
    op.create_index(op.f('ix_user_settings_selected_language_level_id'), 'user_settings', ['selected_language_level_id'], unique=False)
    op.create_index(op.f('ix_user_settings_system_language_level_id'), 'user_settings', ['system_language_level_id'], unique=False)
    op.create_foreign_key(None, 'user_settings', 'language_levels', ['system_language_level_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'user_settings', 'language_levels', ['selected_language_level_id'], ['id'], ondelete='SET NULL')
    op.add_column('words_en', sa.Column('level', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words_en', 'level')
    op.drop_constraint(None, 'user_settings', type_='foreignkey')
    op.drop_constraint(None, 'user_settings', type_='foreignkey')
    op.drop_index(op.f('ix_user_settings_system_language_level_id'), table_name='user_settings')
    op.drop_index(op.f('ix_user_settings_selected_language_level_id'), table_name='user_settings')
    op.alter_column('user_settings', 'timezone',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_server_default=sa.text("'UTC'::character varying"))
    op.drop_column('user_settings', 'reminder_time')
    op.drop_column('user_settings', 'reminders_enabled')
    op.drop_column('user_settings', 'system_language_level_id')
    op.drop_column('user_settings', 'selected_language_level_id')
    # ### end Alembic commands ###
